name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # spaCy 3.8.0 supports Python versions >=3.9 and <3.13
  - spacy=3.8.0
  - pandas
  - geopandas
  - matplotlib
  - numpy>=2.0.0  # spaCy 3.8.0 requires numpy version 2.0.0 or higher
  - shapely
  - scikit-learn
  - scipy
  - opencv
  - pytesseract
  - number-parser
  - requests
  - beautifulsoup4
  - lxml  # Optional, speeds up BeautifulSoup parsing
