city
country
description
location
state
state_abbrev
longitude
latitude
city_longitude
city_latitude
date_occured
Audio	
Visual	
Time of Day	
Apparition Type	
Event Type	
witness count	
total_deaths	
%_under_21	
daylight_minutes	
daylight_diff	
geometry	
buffer_10_miles	
schools_within_10_miles	
distance_to_nearest_school_km	
is_haunted_place_a_school	
Avg_PRCP	
Avg_SNWD	
Diurnal Temperature Range (DTR)	
intrastate_gaspipe_within_10miles	
interstate_gaspipe_within_10miles	
mental_health_provider	
mental_health_RGB