name: ds550
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # spaCy 3.8.0 supports Python versions >=3.9 and <3.13
  - spacy
  - spacy-model-en_core_web_sm
  - pandas
  - geopandas
  - matplotlib
  - numpy>=2.0.0
  - shapely
  - scikit-learn
  - scipy
  - opencv
  - pytesseract
  - regex
  - requests
  - beautifulsoup4
  - lxml
  - tqdm
  - pip  # Ensure pip is installed
  - pip:
      - number-parser
